debug: false
nameservers:
  - 8.8.8.8:53
  - 8.8.4.4:53
  - 1.1.1.1:53
configUpdate: true
updateInterval: 1m
address:
  .local: 127.0.0.1
ipsets:
  vpn:
    - graylog.org
    - .ua
    - mattermost.com
    - redis.io
    - amazon.com
    - googlevideo.com
    - jetbrains.com
    - discord.gg
    - discord.com
    - discordapp.com
    - discordapp.net
    - discord-attachments-uploads-prd.storage.googleapis.com
