debug: false
nameservers:
  - 77.88.8.8:853:common.dot.dns.yandex.net
  - 8.8.8.8:853:dns.google
  - 8.8.4.4:853:dns.google
  - 1.1.1.1:853:cloudflare-dns.com
  - 1.0.0.1:853:cloudflare-dns.com
#  - 8.8.8.8:53
#  - 8.8.4.4:53
#  - 77.88.8.8:53
#  - 77.88.8.1:53
configUpdate: true
updateInterval: 1m
#host: localhost
#port: 10053
address:
  .local: 127.0.0.1
ipsets:
  vpn:
    - graylog.org
    - mattermost.com
    - redis.io
    - amazon.com
    - youtube.com
    - googlevideo.com
    - jetbrains.com
    - clamav.net
    - chatgpt.com
    - twitter.com
    - x.com
    - twimg.com
    - t.co
